### ISSUE TITLE
Metadata Timeout Issue

### ISSUE THREAD

**Issue by colbyford** [microsoft/dicom-server#1871] opened 2022-08-15 21:04 UTC
After deploying the [Azure DICOM service with OHIF viewer](https://github.com/microsoft/dicom-ohif), I am experiencing an issue with certain studies that have a large number of instances.

For example, in the following series of 700+ images, the loading never completes:
![image](https://user-images.githubusercontent.com/3814088/184717396-1a05ffe4-0510-4827-9fdd-80565ac925de.png)

With help from @smithago, we've determined that OHIF is doing a WADO metadata get on the series and cancelling the request after 3 seconds.

This issue does not occur for studies with small numbers of instances.

**Comment by smithago** [comment] 2022-09-02 00:58
Tried reproducing with 300 files, did not reproduce. Also noticed from the picture in the issue, it shows 779 instances, meaning metadata was returned, it was then going to retirve the instance one at a time.

**Comment by smithago** [comment] 2022-09-07 05:38
Cannot reproduce. closing

**Closed by smithago** 2022-09-07 05:38 UTC
Labels: Performance
